#!/usr/bin/env python3
"""
This module contains functions that interpolate between two low-symmetry
structures relative to a high-symmetry structure
"""
import os
from glob import glob
from isodistortfile import isodistort as isod
from ase.io import read, write

class StructureInterp:
    """
    Class for the interpolation between two low-symmetry structures with
    different order parameters relative to a high-symmetry structure.
    """

    def __init__(self, HSfile, LS1file, LS2file):
        self.HS = os.getcwd() + '/' + HSfile
        self.LS1 = os.getcwd() + '/' + LS1file.replace(".cif", "_nlp.cif")
        self.LS2 = os.getcwd() + '/' + LS2file.replace(".cif", "_nlp.cif")


    def reduce_common_subgroup(subgroup=56, latfile=0):
        """
        This function reduces the two low-symmetry files to a common subgroup
        with common lattice parameters.

        Parameters:
        ----------
        subgroup: int
            The number corresponding to the space group of the common subgroup
            to both low-symmetry structures.

        cellparams: int
            The lattice parameters to use for the common reduction of both
            low-symmetry structures. 0: high-symmetry file, 1: low-symmetry
            file 1, 2: low-symmetry file 2.

        Returns:
        --------
        LS#file_"subgroup".cif: file
            Two CIF files in the same directory for the two reduced structures
        """

        #Get lattice parameters of chosen structure and output strutures with
        #normalised lattice parameters (nlp)
        flist = [HSfile, LS1file, LS2file]
        try:
            cell = read(flist[latfile]).cell
            for i, struc in enumerate(flist[1:]):
                Crystal = read(struc)
                Crystal.set_cell(cell)
                write(struc.replace(".cif", "_nlp.cif"), Crystal)
        except IndexError:
            print("latfile must be equal to 0, 1, or 2. Or the wrong files are\
                    present.")
            raise ValueError




        #Re-write CIF files with chosen lattice parameters
        






